In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

1. Bring data.
2. Train/test split.
3. Create model.
4. Evaluate model.

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [5]:
X, y = iris.data, iris.target

In [14]:
#import pandas as pd

In [13]:
#pd.DataFrame(X, columns=['petal1','petal2', 'sepal1','sepal2'])

In [8]:
set(y)

{0, 1, 2}

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y, 
                                                    random_state=42, train_size=0.8, test_size=0.2) 

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
clf = LogisticRegression()

In [22]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
clf.score(X_test, y_test)

1.0

In [27]:
y_pred = clf.predict(X_test)

In [28]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [29]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
confusion_matrix(y_test, y_pred)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [32]:
from sklearn.metrics import classification_report

In [34]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



In [35]:
import pandas as pd

In [ ]:
pd.read_sql()